apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8082 //application running on
    protocol: TCP
  selector:
    app: spring-boot-app
